apiVersion: v2
name: prometheus
description: A Helm chart for prometheus homelab service
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - homelab
  - prometheus
home: https://homelab.local
maintainers:
  - name: homelab
    email: admin@homelab.local
