apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
    service: dns
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: pihole-pool
spec:
  type: {{ .Values.service.dns.type }}
  {{- if .Values.service.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.dns.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.dns.ports.udp }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.dns.ports.tcp }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}