apiVersion: v2
name: grafana
description: A Helm chart for grafana homelab service
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - homelab
  - grafana
home: https://homelab.local
maintainers:
  - name: homelab
    email: admin@homelab.local
